# Building
pack_directory = "./src"
output_file_path = "resources.zip"

# Optimization
recompress_compressed_files = true

# Obfuscation
zip_spec_conformance_level = "disregard"
size_increasing_zip_obfuscation = true
percentage_of_zip_structures_tuned_for_obfuscation_discretion = 100
