name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate pack.mcmeta
        run: echo '{"pack":{"pack_format":8,"description":"§lGauntlet §r| ${{ github.run_number }}"}}' > src/pack.mcmeta

      - name: Optimize Pack
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest
          options: packsquash.toml

      - name: Hash Pack
        id: hash
        run: echo "hash=$(sha1sum 'resourcepack.zip' | awk '{print $1}')" >> $GITHUB_OUTPUT

      - name: Create Manifest
        id: manifest
        run: echo '{"name":"${{ steps.hash.outputs.hash }}-resourcepack.zip","sha1":"${{ steps.hash.outputs.hash }}"}' > manifest.json
          
      - name: Upload
        run: |
          curl -X 'POST' \
            'https://maven.resourcefulbees.com/service/rest/v1/components?repository=Gauntlet' \
            -H 'accept: application/json' \
            -H 'Content-Type: multipart/form-data' \
            -H 'Authorization: Basic ${{ secrets.MAVEN_TOKEN }}' \
            -F 'raw.directory=/' \
            -F 'raw.asset1=@resourcepack.zip;type=application/zip' \
            -F 'raw.asset1.filename=${{ steps.hash.outputs.hash }}-resourcepack.zip' \
            -F 'raw.asset2=@manifest.json;type=application/json' \
            -F 'raw.asset2.filename=manifest.json'

      - name: Tell Server
        run: |
          curl -X 'POST' \
            'https://api.exaroton.com/v1/servers/${{ vars.SERVER_ID }}/command/' \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer ${{ secrets.EXAROTON_TOKEN }}' \
            -d '{"command":"tellraw @a \"§9§l-----------[§aGauntlet Build Server§9§l]-----------§r\\n§9Commit Uploader:§7 ${{ github.actor }}!§r\\n§9Commit Message:§7 ${{ github.event.head_commit.message }}\\n§l---------------------------------------\""}'

      - name: Reload Server
        run: |
          curl -X 'POST' \
            'https://api.exaroton.com/v1/servers/${{ vars.SERVER_ID }}/command/' \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer ${{ secrets.EXAROTON_TOKEN }}' \
            -d '{"command":"reload-resourcepack"}'
