name: Discord Notification

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Get Commit Message
        run: echo "COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.event.after }})" >> $GITHUB_ENV

      - name: Send Discord Notification
        run: |
          curl -X 'POST' \
            '${{ secrets.DISCORD_WEBHOOK_URL }}' \
            -H 'Content-Type: application/json' \
            -d '{
              "username": "GitHub Actions Bot",
              "embeds": [{
                "title": "New Commit from ${{ github.actor }}",
                "description": "${{ env.COMMIT_MESSAGE }}",
                "color": 15258703,
                "fields": [
                  {
                    "name": "Repository",
                    "value": "${{ github.repository }}",
                    "inline": true
                  },
                  {
                    "name": "Branch",
                    "value": "${{ github.ref }}",
                    "inline": true
                  }
                ],
                "footer": {
                  "text": "Commit ID: ${{ github.sha }}"
                }
              }]
            }'
